name: sample-workflow
on:
  push:
    branches:
      - master

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout step
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Prepare machine
        run: |
          python -m pip install --upgrade pip

      - name: Bump version and push tag
        uses: endrjuskr/github-tag-action@master
        id: bump_dry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true

      - name: Checkout bump
        run: |
          pip install -r requirements.txt

      - name: Checkout bump 2
        run: |
          bump2version --new-version ${{ steps.bump_dry.outputs.new_tag }} patch setup.py

      - uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Start new version
          branch: master

      - name: Bump version and push tag
        uses: endrjuskr/github-tag-action@master
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{steps.bump_dry.outputs.part}}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          release_name: Release ${{steps.bump.outputs.part}} ${{ steps.bump.outputs.new_tag }}
          draft: true

